### ISSUE TITLE
I can't train my private dataset

### ISSUE THREAD

**Issue by seadhy** [pythonlessons/mltu#19]
I'm trying to use [captcha to text](https://www.youtube.com/watch?v=z_6P0PilBmM) but I can't train my dataset like you. 
When I tried with the dataset you gave, it worked without any problems, but when I changed my own images with yours, I had problems. A few examples from my dataset with 10129 images:

![000a2544266070484f9e651067d41b1e-jhlh](https://github.com/pythonlessons/mltu/assets/82868382/bafec0ec-e17a-4d89-a4e0-8f7bb285158b)
![000db107392d7af6a5a5239286724ea1-hlfg](https://github.com/pythonlessons/mltu/assets/82868382/d3f46187-185d-47a5-87ca-0b3e80e57423)
![0a9474ddd6ca48343277b8dd9ba4aaea-rulr](https://github.com/pythonlessons/mltu/assets/82868382/38c8aaaa-e16e-4129-a192-370728072331)

I made a change in `train.py` file like this:
 `label = os.path.splitext(file)[0]` -> ` label = os.path.splitext(file)[0].split('-')[1]`.

 Because the names of my images are not captcha_answer.png like yours, but md5hash-captcha_answer.png. So I made a change in this way and made it take the captcha_answer parameter in the same way.

In the `config.py` file, since all my images are 350x100, I changed `self.height = 100` and `self.width = 350`. Then I got the following error. Can you help me solve this?

![image](https://github.com/pythonlessons/mltu/assets/82868382/3a9a33e9-4cf7-49f7-b705-47522cdfc724)

**Comment by pythonlessons** [comment]
It would help if you modified the model according to your input shapes. I believe if you will set self.height = 50 and self.width = 200 as it was initially, everything will be ok. Check this out

**Comment by seadhy** [comment]
I changed it but I keep getting the same error
![image](https://github.com/pythonlessons/mltu/assets/82868382/10777b89-2b87-470a-862a-7f9f8b996b28)

**Comment by pythonlessons** [comment]
I think you are inputing None to the model, check this first (if you really receive images from dataprovider)

**Comment by seadhy** [comment]
I'm sure about this. Please watch the video:
https://streamable.com/3f16yn

**Comment by pythonlessons** [comment]
If you can upload somewhere your dataset and code you showed here, I'll try it by myself

**Comment by seadhy** [comment]
You can download 100 images of my dataset and the train.py file I changed from this link.
https://www.mediafire.com/file/4b8l1qdmeya8bp1/dataset_and_train_file.rar/file

**Comment by pythonlessons** [comment]
ok mate, I tested it out and it seems that cv2.imread(file_path) returns None. So it means that your images are in some kind format some opencv can't handle it up. So either fix your images or find a way to read them using different method. But I prefer fixing them, try to read them in pillow and save them with cv2, this should solve this

**Comment by pythonlessons** [comment]
train for unlimited epochs, for example for 1000 epochs, and EarlyStopping at some point will work. Then train another model with a different input size until it stops. And choose whether the model gives you better accuracy in terms of CER, 1000 images are a pretty small dataset, you may increase accuracy by adding more images. Overall, images are pretty simple, so it should take for long to train both of these models

**Comment by seadhy** [comment]
Should I leave the self.height and self.width values ​​at their default values ​​of 50, 200 or change them to 100, 350 the same as my images?

**Comment by pythonlessons** [comment]
> Should I leave the self.height and self.width values ​​at their default values ​​of 50, 200 or change them to 100, 350 the same as my images?
> 
> It saves onnx and csv files only after all epochs are finished. But he was recording every time on video. What is the reason of this?

Usually, smaller input size, means faster inference model, higher input size slower inference but better accuracy. So that's why you should train both models and see whether bigger input size does impact to the accuracy.

> It saves onnx and csv files only after all epochs are finished. But he was recording every time on video. What is the reason of this? Can you explain this in more details? What you mean? it saves .h5 best model every epoch, and after training finishes it loads these weights and converts model into onnx

**Comment by seadhy** [comment]
I seem to have solved the problem but now I have a different problem. I trained the model via Google Colab. I started it with 350x100, 300 epochs and 256 batch_size. It was stopped by Earlystopper at epoch 50. When I tried the model, even with the images it trained, I was getting an empty predict result. When I looked at the file you trained and my own log file, my loss values were almost never decreasing. However, in yours, it decreased and decreased even less than 1. I have shared my results below, can you check and give suggestions?

https://www.mediafire.com/file/o7lj3s3wbz9aolv/202307121335.rar/file

**Comment by seadhy** [comment]
> I seem to have solved the problem but now I have a different problem. I trained the model via Google Colab. I started it with 350x100, 300 epochs and 256 batch_size. It was stopped by Earlystopper at epoch 50. When I tried the model, even with the images it trained, I was getting an empty predict result. When I looked at the file you trained and my own log file, my loss values were almost never decreasing. However, in yours, it decreased and decreased even less than 1. I have shared my results below, can you check and give suggestions?
> 
> https://www.mediafire.com/file/o7lj3s3wbz9aolv/202307121335.rar/file

@pythonlessons Please check. By the way, 2nd tutorial gives an error when I try to use it with the version you updated.

**Comment by pythonlessons** [comment]
thanks, I'll make fix release first

**Comment by pythonlessons** [comment]
Solved.
