### ISSUE TITLE
Config file issue 

### ISSUE THREAD

**Issue by zainulabdinsystems** [pythonlessons/mltu#22]
configs = BaseModelConfigs.load("Models/02_captcha_to_text/202212211205/configs.yaml")

**Comment by pythonlessons** [comment]
you need either to train or download model

**Comment by zainulabdinsystems** [comment]
please give me the download link of modal

**Comment by pythonlessons** [comment]
> please give me the download link of modal

Read https://pylessons.com/tensorflow-ocr-captcha tutorial. There is a link to download model
