### ISSUE TITLE
model.onnx file is not creating

### ISSUE THREAD

**Issue by Zain-ul-abdin0** [pythonlessons/mltu#26]
hi! first of all when I am creating model, onnx file is not generating. And while training model, do we need to name the image with captcha having characters ???????????????????????????????????????????????????????????????????????????????

**Comment by pythonlessons** [comment]
First of all, this is rude to write so much "?". I don't want to help you with such a rude attitude. 
Second, before telling that it's not creating, you should write Python version you use, the tensorflow version and the tf2onnx version.

Naming doesn't matter; it's up to you how you preprocess true labels, either from the name or other source.

Can't help you without any details...

**Comment by johny1122** [comment]
Hi, we have the same issue.

we are using:
- python 3.9.6
- tensorflow 2.13.0
- tf2onnx 1.14.0

There is a problem in convert.py of the tf2onnx library which prints us the error: 
"'funcgraph' object has no attribute '_captures'" in line 457

Thanks!

**Comment by pythonlessons** [comment]
> 

As of new TensorFlow release (2.13.0), tf2onnx  haven't updated their library yet. Downgrade TensorFlow  to 2.12.0 and you'll be good.

**Comment by johny1122** [comment]
Thanks for the fast reply!
We are working on Mac and found that installing `tensorflow-macos` package version 2.12.0 (without installing `tensorflow`) and latest `mltu` version (1.0.15) solved the problem :)

**Comment by pythonlessons** [comment]
Great!
