### ISSUE TITLE
captcha images name issue for training

### ISSUE THREAD

**Issue by zainulabdinsystems** [pythonlessons/mltu#27]
Hi!
FIrst of all thanks alot. Now question is that I am having my 800 images with having image name captch1,captcha2,captcha3 and so on. I want to ask that while training the model, do I need to give the images the solved captcha characters as you gave like x223g,ss23d and 7d7df etc.

**Comment by pythonlessons** [comment]
Naming doesn't matter; it's up to you how you preprocess true labels, either from the name or other source.

**Comment by pythonlessons** [comment]
No response.
