### ISSUE TITLE
Model configuration for new captcha type

### ISSUE THREAD

**Issue by Firdavsbek07** [pythonlessons/mltu#45]
Hello brother, thanks for code and the model that you have made. I'm new to neural networks and ai training.

![0asA](https://github.com/pythonlessons/mltu/assets/93431957/7372071b-55bf-4f29-960b-98236104543f)

![image_1708442297 0910537](https://github.com/pythonlessons/mltu/assets/93431957/a97d7f10-fe28-4840-9ced-2413ca323631)
![image_1708442297 0910537](https://github.com/pythonlessons/mltu/assets/93431957/f435a1ee-8acc-4c61-ab89-ed28e9b2e43a)

I'm trying to train captcha solver model on this captcha types. I didn't succeed yet. First of all, because of when the training is reaching Epoch 200-350/1000, it's printing Epoch: early stopping. At first I tried to change the batch size, number of workers and training speed. 
Tried 32, 64 (default), 128, 256, 270, 512 batch size and 10, 20, 30, 40 training worker amount. 

I used 1000 of those captchas as a dataset and 101 different captchas for testing. The "best" result i got at batch_size=256, train_workers = 30 on a machine with 24GB RAM, used intel i5-12th CPU for training. A trained model result below:
[202402212032.zip](https://github.com/pythonlessons/mltu/files/14393650/202402212032.zip)

Also thought maybe my machine was not powerful enough, so i tried a different machine with 64GB RAM, i9-13th CPU, Nvidia GeForce RTX 2080. Still got the Epoch early stopping error around 313/1000 epoch. The "trained" model folder is in below:
[202402232009 i9.zip](https://github.com/pythonlessons/mltu/files/14393664/202402232009.i9.zip)

Now, i know that i can use of of those models and continue training them. 

i was hoping if you can help to configure the model architcture or configs for those captcha images. I think maybe need to make fit the image size, because while training, I was getting "libpng warning: pHYs: CRC error" a lot. I'd very grateful if you could help me with that. Thanks for your valueable time.

**Comment by Firdavsbek07** [comment]
Also i was wondering whether i can use an svg files for training and use the trained model to predict svg file images
![image_1708442297 0910537](https://github.com/pythonlessons/mltu/assets/93431957/e08dd4e7-5c62-4f5c-9bac-be0d8eb5a81d)

**Comment by ThanhLD24** [comment]
i got the same issue with new dataset of captcha. could @pythonlessons please help us the way how to adjust model architecture to solve other type of captcha.
Here is my one of captcha image:
![12845](https://github.com/pythonlessons/mltu/assets/15336708/f02af490-4b02-4767-bf82-469a91fb094b)
Thank you.

**Comment by pythonlessons** [comment]
Make sure you read your images correctly, to do so you can use OpenCV to show your images while iterating dataProvider. Batch size doesn't have any considerable impact on this; you need to work on model architecture. I made a tutorial just as an example that you can use to continue working on similar tasks.

**Comment by Firdavsbek07** [comment]
Thank you for your reply, it worked better after edited the image sizes in configs.py. Now it's working well.
