### ISSUE TITLE
mltu/Tutorials /01_image_to_word

### ISSUE THREAD

**Issue by Onicki5** [pythonlessons/mltu#47]
Hey 

I use tensorflow 2.4.1 and must change "import keras" to "import tensorflow.keras"

Now i have the follow issues in train.py "model.fit" so in model.py

------------------------------------------------------------------------
Epoch 1/100
Traceback (most recent call last):
  File "c:/Tutorials/TensorFlow/image_to_word/train.py", line 109, in <module>
    model.fit(
  File "C:\appdata\local\programs\python\python38\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1100, in fit
    tmp_logs = self.train_function(iterator)
  File "C:\appdata\local\programs\python\python38\lib\site-packages\tensorflow\python\eager\def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "C:\appdata\local\programs\python\python38\lib\site-packages\tensorflow\python\eager\def_function.py", line 871, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "C:\appdata\local\programs\python\python38\lib\site-packages\tensorflow\python\eager\def_function.py", line 725, in _initialize        
    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
  File "C:\appdata\local\programs\python\python38\lib\site-packages\tensorflow\python\eager\function.py", line 2969, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "C:\appdata\local\programs\python\python38\lib\site-packages\tensorflow\python\eager\function.py", line 3361, in _maybe_define_function    graph_function = self._create_graph_function(args, kwargs)
  File "C:\appdata\local\programs\python\python38\lib\site-packages\tensorflow\python\eager\function.py", line 3196, in _create_graph_function    func_graph_module.func_graph_from_py_func(
  File "C:\appdata\local\programs\python\python38\lib\site-packages\tensorflow\python\framework\func_graph.py", line 990, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "C:\appdata\local\programs\python\python38\lib\site-packages\tensorflow\python\eager\def_function.py", line 634, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "C:\appdata\local\programs\python\python38\lib\site-packages\tensorflow\python\framework\func_graph.py", line 977, in wrapper
    raise e.ag_error_metadata.to_exception(e)
TypeError: in user code:

    C:\appdata\local\programs\python\python38\lib\site-packages\tensorflow\python\keras\engine\training.py:805 train_function  *
        return step_function(self, iterator)
    C:e\appdata\local\programs\python\python38\lib\site-packages\tensorflow\python\keras\engine\training.py:795 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    C:\appdata\local\programs\python\python38\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:1259 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    C:\appdata\local\programs\python\python38\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2730 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    C:\appdata\local\programs\python\python38\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:3417 _call_for_each_replica
        return fn(*args, **kwargs)
    C:\appdata\local\programs\python\python38\lib\site-packages\tensorflow\python\keras\engine\training.py:788 run_step  **
        outputs = model.train_step(data)
    C:\appdata\local\programs\python\python38\lib\site-packages\tensorflow\python\keras\engine\training.py:759 train_step
        return {m.name: m.result() for m in self.metrics}
    C:\appdata\local\programs\python\python38\lib\site-packages\tensorflow\python\keras\engine\training.py:759 <dictcomp>
        return {m.name: m.result() for m in self.metrics}
    C:\appdata\local\programs\python\python38\lib\site-packages\tensorflow\python\keras\utils\metrics_utils.py:122 decorated
        result_t = array_ops.identity(result_fn(*args))
    C:\appdata\local\programs\python\python38\lib\site-packages\tensorflow\python\util\dispatch.py:201 wrapper
        return target(*args, **kwargs)
    C:\appdata\local\programs\python\python38\lib\site-packages\tensorflow\python\ops\array_ops.py:287 identity
        ret = gen_array_ops.identity(input, name=name)
    C:\appdata\local\programs\python\python38\lib\site-packages\tensorflow\python\ops\gen_array_ops.py:3941 identity
        _, _, _op, _outputs = _op_def_library._apply_op_helper(
    C:\appdata\local\programs\python\python38\lib\site-packages\tensorflow\python\framework\op_def_library.py:525 _apply_op_helper
        raise err
    C:\appdata\local\programs\python\python38\lib\site-packages\tensorflow\python\framework\op_def_library.py:517 _apply_op_helper
        values = ops.convert_to_tensor(
    C:\appdata\local\programs\python\python38\lib\site-packages\tensorflow\python\profiler\trace.py:163 wrapped
        return func(*args, **kwargs)
    C:\appdata\local\programs\python\python38\lib\site-packages\tensorflow\python\framework\ops.py:1540 convert_to_tensor
        ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
    C:\appdata\local\programs\python\python38\lib\site-packages\tensorflow\python\framework\constant_op.py:339 _constant_tensor_conversion_function
        return constant(v, dtype=dtype, name=name)
    C:\appdata\local\programs\python\python38\lib\site-packages\tensorflow\python\framework\constant_op.py:264 constant
        return _constant_impl(value, dtype, shape, name, verify_shape=False,
    C:\appdata\local\programs\python\python38\lib\site-packages\tensorflow\python\framework\constant_op.py:281 _constant_impl
        tensor_util.make_tensor_proto(
    C:\appdata\local\programs\python\python38\lib\site-packages\tensorflow\python\framework\tensor_util.py:457 make_tensor_proto
        _AssertCompatible(values, dtype)
    C:\appdata\local\programs\python\python38\lib\site-packages\tensorflow\python\framework\tensor_util.py:334 _AssertCompatible
        raise TypeError("Expected any non-tensor type, got a tensor instead.")

    TypeError: Expected any non-tensor type, got a tensor instead.

------------------------------------------------------------------------

**Comment by pythonlessons** [comment]
Install at least 2.10 tensorflow version or change these imports manually.
