### ISSUE TITLE
Regarding Classification of Handwritten text and printed text

### ISSUE THREAD

**Issue by shaikalfaaz** [pythonlessons/mltu#51]
Hi sir 

Do you know any pre-trained models that classify texts whether it is handwritten or printed 
If not can you please tell me how to build a model from scratch to classify handwritten and printed texts by ignoring other languages in the image 
So in my use case I will have cropped image portions similar to captcha sizes I want to detect whether those cropped portions have handwritten text in them or not 

I do not have other ways to communicate with you that's why I'm raising an issue I am extremely sorry from my end 
Hoping for a response from you sir 
@pythonlessons

**Comment by pythonlessons** [comment]
Hello @shaikalfaaz. Unfortunately I don't know such open-source datasets. But you can create one, by takin handwritten dataset and some kind of OCR datasets as printed text. You need to use some basic classifier for this task.
