### ISSUE TITLE
version 1.2.5? I saw there's a wheel, but what is the release?

### ISSUE THREAD

**Issue by seidnerj** [pythonlessons/mltu#52]
Can't see a tag or release on github.

Thanks!

**Comment by seidnerj** [comment]
I assume it is this commit:
https://github.com/pythonlessons/mltu/commit/6daf202509b897740a0bd287f32c53baccfb8c1f

But it would be good to have a "proper" tag and equivalent release 🙏

**Comment by pythonlessons** [comment]
@seidnerj Thank you for this, somehow made a release, but forgot to make it on GitHub... doing it now

**Comment by pythonlessons** [comment]
@seidnerj Thank you, made a release :)

**Comment by seidnerj** [comment]
Thank you 🙂🙏
